name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "npm install"

      - name: Build step
        run: npm run build
        env:
          NITRO_PRESET: deno_deploy

      - name: Upload to Deno Deploy
        run: |
          # 1. Setup
          deno install -A -f -g jsr:@deno/deployctl
          export PATH="$HOME/.deno/bin:$PATH"

          # 2. Deploy the server entrypoint file, explicitly including the public folder.
          # This tells deployctl to use index.ts as the entrypoint and to bundle 
          # the entire .output/public directory contents alongside it.
          /home/runner/.deno/bin/deployctl deploy .output/server/index.mjs \
            --project=shpunter-backtesting \
            --include=./.output/public \
            --include=./.output/nitro.json # Including nitro.json for good measure
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}